import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        body: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        headline: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        code: ['monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        sidebar: { DEFAULT: 'hsl(var(--sidebar-background))', foreground: 'hsl(var(--sidebar-foreground))' },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 4px)',
        sm: 'calc(var(--radius) - 8px)',
      },
      keyframes: {
        'splat': { '0%': { transform: 'scale(1)', opacity: '1' }, '100%': { transform: 'scale(0)', opacity: '0' } },
        'fall': { '0%': { transform: 'translateY(0) scale(1)', opacity: '1' }, '100%': { transform: 'translateY(600px) scale(0.5)', opacity: '0' } },
        'flash': { '0%': { opacity: '0' }, '50%': { opacity: '0.8' }, '100%': { opacity: '0' } },
        'combo': {
          '0%': { transform: 'scale(0) rotate(-10deg)', opacity: '0' },
          '30%': { transform: 'scale(1.4) rotate(5deg)', opacity: '1' },
          '50%': { transform: 'scale(0.9) rotate(-2deg)' },
          '70%': { transform: 'scale(1.1) rotate(1deg)' },
          '100%': { transform: 'scale(1) rotate(0deg)', opacity: '1' },
        },
        'shake-screen': {
          '0%,100%': { transform: 'translate(0,0)' },
          '10%': { transform: 'translate(-8px,-4px)' },
          '20%': { transform: 'translate(6px,3px)' },
          '30%': { transform: 'translate(-10px,5px)' },
          '40%': { transform: 'translate(8px,-3px)' },
          '50%': { transform: 'translate(-6px,4px)' },
          '60%': { transform: 'translate(10px,-5px)' },
          '70%': { transform: 'translate(-4px,2px)' },
          '80%': { transform: 'translate(5px,-2px)' },
          '90%': { transform: 'translate(-2px,1px)' },
        },
        'color-shake': {
          '0%,100%': { transform: 'translate(0, 0) scale(1)' },
          '15%': { transform: 'translate(-12px, -8px) scale(1.1)' },
          '30%': { transform: 'translate(10px, 6px) scale(1.15)' },
          '45%': { transform: 'translate(-14px, 9px) scale(1.2)' },
          '60%': { transform: 'translate(12px, -7px) scale(1.15)' },
          '75%': { transform: 'translate(-8px, -5px) scale(1.1)' },
          '90%': { transform: 'translate(5px, 4px) scale(1.05)' },
        },
        'color-explode': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '20%': { transform: 'scale(1.3)', opacity: '1' },
          '50%': { transform: 'scale(2)', opacity: '0.8' },
          '80%': { transform: 'scale(3)', opacity: '0.4' },
          '100%': { transform: 'scale(5)', opacity: '0' },
        },
        'color-flash': {
          '0%': { opacity: '0' },
          '20%': { opacity: '0.8' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'splat': 'splat 0.3s ease-out forwards',
        'fall': 'fall 1s cubic-bezier(0.55,0.085,0.68,0.53) forwards',
        'flash': 'flash 0.2s ease-out forwards',
        'combo': 'combo 0.6s cubic-bezier(0.68,-0.55,0.265,1.55) forwards',
        'shake-screen': 'shake-screen 0.5s ease-out',
        'color-shake': 'color-shake 0.5s ease-in-out',
        'color-explode': 'color-explode 0.6s ease-out forwards',
        'color-flash': 'color-flash 0.5s ease-out forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
